### ISSUE TITLE
Collision name of runs on multiple servers

### ISSUE THREAD

**Issue by franchuterivera** [openml/automlbenchmark#114]
Currently, the name of a run follows the principle:

now_str = datetime_iso(date_sep='', time_sep='')
sid = (args.session if args.session is not None
       else "{}_{}".format('_'.join([args.framework,
                                     os.path.splitext(os.path.basename(args.benchmark))[0],
                                     args.constraint,
                                     extras.get('run_mode', args.mode)])
                              .lower(),
                           now_str))
Sadly, when launching the benchmark on a mega cluster, multiple runs are allocated at the same time for different folds and same framework.

I will like to suggest a better sid name through this issue and its related PR

**Comment by sebhrusen** [comment]
@franchuterivera you can already specify your own sid using the `--session` parameter if you're afraid of conflicts.
I'd be interested in knowing how you managed to get a conflict exactly: it means you're running the same benchmark (same framework, same benchmark, same constraints) multiple times in parallel (triggered in the same second). I don't understand the objective. It really looks like a corner case, and in this case, I would encourage to specify the sid as mentioned above, instead of making it even more complex just to handle this specific use-case.

**Comment by franchuterivera** [comment]
Yeah, makes sense. I missed the -session support honestly

We run the folds separated, do to some result restriction. As the fold is not included in the sid it crashed. I can achieve what I want to do with the -session so I will close this issue

**Comment by sebhrusen** [comment]
Thanks @franchuterivera.
`--session` parameter, like the `-X` one (which allows to override any config defined in `config.yaml` from the command line) are a bit hidden and not documented mainly because they don't propagate to `docker` or `ec2` instances, so you need to clearly understand how they work to use them without false expectations.

But in your case, I'm glad that `--session` is just what you need.
