### ISSUE TITLE
Error while using a custom benchmark on AutoWEKA

### ISSUE THREAD

**Issue by Stefanenrichard** [openml/automlbenchmark#30]
Hi there,

While using my own set of benchmark datasets to test AutoWEKA on AWS, I get an error that some files are not created. I do not run into this error while running other AutoML methods on the same benchmark set. When running AutoWEKA with other sets (test and 2small ch1) this error does not occur.

Attached is the log file and the benchmark set, the benchmark set is converted to .txt for upload purposes.
[benchmarkhealthcare.txt](https://github.com/openml/automlbenchmark/files/3320466/benchmarkhealthcare.txt)

[runbenchmark_20190624T104333.log](https://github.com/openml/automlbenchmark/files/3320443/runbenchmark_20190624T104333.log)

**Comment by seb-h2o** [comment]
Hi @Stefanenrichard,
- yes, we could do better than raising a `FileNotFoundError` here: this is raised because AutoWEKA previously failed but for some reason that I need to investigate, the error is not propagated. However, the app raises a new error later when trying to read the predictions.
- the reason why AutoWEKA fails is due to spaces in the task names in your benchmark set. I'm actually even surprised that it still works with other frameworks: I'd recommend to replace spaces with dashes or underscores for now, creating a ticket to automate this on app side.

**Comment by seb-h2o** [comment]
> we could do better than raising a FileNotFoundError here: this is raised because AutoWEKA previously failed but for some reason that I need to investigate, the error is not propagated. 

well, it seems to be mainly AutoWEKA's fault here: the command fails but return code is still 0...

**Comment by Stefanenrichard** [comment]
Hi Seb, 

Thanks for helping me out again! :)

**Comment by seb-h2o** [comment]
You're welcome!
