### ISSUE TITLE
Benchmark does not use OpenML cache directory by default

### ISSUE THREAD

**Issue by PGijsbers** [openml/automlbenchmark#321]
`runbenchmark.py` explicitly specifies the input directory, which is used as cache:
```python
default_dirs = ns(
    input_dir="~/.openml/cache",
    ...
)
```
but the default is normally `~/.openml/` ([specifics](https://openml.github.io/openml-python/develop/usage.html#configuration)), but can also be configured by the user (in the openml configuration).
Wouldn't it be better to only use `input_dir` if it is set in the benchmark configuration, and make the default of the benchmark fall back on whatever OpenML decides the openml cache directory is?

Or was this on purpose because we add additional files there (i.e. split files)? If so, wouldn't it be better to have a mirror directory with _just_ those extra files, and not the entire dataset/metadata files as well?

**Comment by sebhrusen** [comment]
Default openml-client cache folder used to be "~/.openml/cache" (at least on Linux/macOS), hence this default.
Btw, the link provided above mentions:
```text
cachedir:
        if not given, will default to ~/.openml/cache
```

I'm not convinced that supporting multiple `input` folders would be useful: it will just add complexity and its share of bugs as `input_dir` is used to share data in `container` mode, and to potentially upload data to ec2 instances.
Actually, I tend to think that defaulting to the `openml` cache folder is not even that useful, and we could as well point default `input_dir` to `~/.config/automlbenchmark/data`

**Comment by PGijsbers** [comment]
> Btw, the link provided above mentions:

Hm, I'll take it up with `openml-python` devs to see what we do here. Thanks for pointing that out 🤦‍♂️ 
But either way I think we could avoid a hard-coded path, since I think the user's openml configuration file should be leading when deciding where the openml cache folder is (imo). The `openml` section in `config.yaml` can then be used to overrule any options from the `.openml/config` file.

> I'm not convinced that supporting multiple input folders would be useful...

I think it makes most sense to have an input directory (for custom datasets) and be able to share the openml cache directory in addition. Perhaps we can load from the openml cache but write any fold-files to the amlb input directory? You shouldn't need to access the openml cache directly, just through openml. The benefit of using the openml cache is mostly for local mode, where a user could first use `openml` to see what tasks/studies they find interesting (already downloading them for that purpose), and then run the benchmark (without redownloading the datasets they just downloaded).

**Comment by sebhrusen** [comment]
> The openml section in config.yaml can then be used to overrule any options from the .openml/config file.

Looks okayish at first sight, but I still don't like it.
So basically, for ec2 instances, once we start storing openML data on s3 to optimize downloads/workload on openml servers, we'll have to additionally set `openml.input_dir` as a command line argument so that it takes precendence over the value in the user's `config.yaml`, which takes precedence over the default `input_dir` that we already enforce… that's the reason I'd like to keep one single input folder, openml or not: whatever the solution, it will always make the ec2 integration more difficult.
Same with docker: the advantage of the current aprroach is that when you run the image, the `input_dir` is mapped so that the docker instance doesn't need to download the data gain. If you add a second switch, you'll get more use cases that you'll have to handle correctly.

Your proposition looks good on the paper, but I feel like it's much more complicated to get right than you think.

**Comment by PGijsbers** [comment]
Thanks for the insight. In that case I'll close the issue.
