### ISSUE TITLE
AWS instance running out of memory

### ISSUE THREAD

**Issue by Stefanenrichard** [openml/automlbenchmark#33]
When trying to reproduce your benchmark test using my own datasets on the m5.2xlarge instances on aws for 4 hours with 10k cross validation run into the AWS error  `OSError: [Errno 28] No space left on device` for Auto-WEKA and autosklearn (see logs). My benchmark file is also attached. Hyperopt and TPOT seem to function pretty well. Both autoweka and autosklearn have functioned properly on the test runs on the free tier of AWS. Is there something wrong in my configuration? I changed the amount of cores from 2 to 8 in my benchmark test file, due to the machinery upgrade.

[benchmarkhealthcare.txt](https://github.com/openml/automlbenchmark/files/3325959/benchmarkhealthcare.txt)

[runbenchmark_20190625T134539.log](https://github.com/openml/automlbenchmark/files/3325944/runbenchmark_20190625T134539.log)
[runbenchmark_20190625T122444.log](https://github.com/openml/automlbenchmark/files/3325945/runbenchmark_20190625T122444.log)

**Comment by seb-h2o** [comment]
@Stefanenrichard The instance seems to be running out of disk space, and it's very surprising indeed as your datasets look quite small.

As you're running all the benchmark tasks on one single instance (no parallelization), it's easy to fill the disk just with data when there are too many tasks + large datasets running on the same instance. The recommended practice is to run multiple ec2 instances in parallel for a fair comparison so that each ec2 instance runs only one single task with a clean setup: for 2 instances in parallel,
```python runbenchmark.py autosklearn healthcare -m aws -p 2```.
The amount of instances you can use at once is limited by your AWS account.
Again, given your datasets and the fact that it works for other frameworks, I don't think it will solve the issue.

Actually, there are a few things I don't understand in the logs: why in both `autosklearn` and `AutoWEKA`, it jumps from `Liver, fold 0` to `Sick, fold 0 to 9`? Can you please check that it's running all tasks and all folds for other frameworks?

Also `autosklearn` can write a lot on the file system when exploring the hyperparameter space, so it might be the reason. Can't remember seeing this behaviour with `AutoWEKA` though but it's possible it does the same.
Usually you can increase disk space on the ec2 instance using the `min_vol_size_mb` config in the benchmark definition (see in`resources/benchmarks` folder for examples), but I'm not sure this will help in your case.

Let me try it with the published docker images, and I'll tell you if it works.

**Comment by seb-h2o** [comment]
Btw, I've seen in the logs that you're still on the fix branch: you can switch back to `master` now.
Also, if you want to use published docker images: we know they work fine as they've been used for the paper on the https://openml.github.io/automlbenchmark/ website, you just need to activate it in your custom `config.yaml`:
`aws.use_docker: true`
Also ensure that you don't have a custom `project_repository` in that same file, as it's used to pick the default docker image version.

**Comment by seb-h2o** [comment]
After modifying your `healthcare` benchmark to run it for only `10mn` on `fold 0` only, I tried to run it with the `automlbenchmark/autosklearn` docker image on AWS and it's writing a shitload on the disk indeed, about 15% of the disk (8GB by default -> 1.2GB) for 10mn only!

If you really plan to run those tasks for 4h, I'd advice to make your calculations and set the `min_vol_size_mb` accordingly (keep let's say 4GB for the system + the docker image if you want to use it): you can be generous, disk space is pretty cheap.
Also, you'll need to run multiple instances in parallel to avoid accumulation of `autosklearn` generated files on your drive.

FYI, you can test only 1 task / 1 fold first maybe:
```python runbenchmark.py autosklearn healthcare -t Liver -f 0 -m aws```
and if it works, you can then run them all in parallel:
```python runbenchmark.py autosklearn healthcare -m aws -p 4```

**Comment by Stefanenrichard** [comment]
Hi Seb,

Thanks again for the fine investigation into my problems and helping to solve them. As I read your paper again I noted that there was only a slight improvement of the 4h scores over the 1 hour scores. Hence I'll first try to adapt the benchmark to only run for one hour and see what happens. Although Iooking at the time in the logs it will most probably still draw an error. 

Every method is on a seperate instance, to make the comparison as fair as possible. I'll keep you up to date with what will be the final solution to solve this.

**Comment by Stefanenrichard** [comment]
Hi Seb,

After a trying a few of your suggestions I altered the benchmark file with `min_vol_size_mb` as you use it on the large 4h runs. I hope this is sufficient for the disk size. The first few folds have passed, so that is a good sign. Thanks again for your knowledge :)

**Comment by seb-h2o** [comment]
Hi @Stefanenrichard, great! I'm still surprised that those frameworks are writing so much on the disk with those rather small datasets. Maybe it's because iterations are faster and it writes gazillion of models.

See those tickets for `autosklearn`:
https://github.com/automl/auto-sklearn/issues/454
https://github.com/automl/auto-sklearn/issues/665

**Comment by Stefanenrichard** [comment]
Hi Seb, Auto-WEKA is doing completely fine. However I still have problems with getting to get autosklearn run. When running the autosklearn with `aws.use_docker` is false I get this error. (on the old repo) 
[runbenchmark_20190626T145600.log](https://github.com/openml/automlbenchmark/files/3330760/runbenchmark_20190626T145600.log)

When using the `aws.use_docker` = true, I seem to miss the docker image  (on the old repo)
[runbenchmark_20190626T151203.log](https://github.com/openml/automlbenchmark/files/3330761/runbenchmark_20190626T151203.log)

When running the benchmark using docker on a separate pull location, here I do not get an error. But I also do not get results. (on the freshly pulled repo)
[runbenchmark_20190626T152448.log](https://github.com/openml/automlbenchmark/files/3330828/runbenchmark_20190626T152448.log)


p.s. I just pulled all the latest files from the git, just did not rename my home repository as the running processes need to write their results there in the results folder.

**Comment by seb-h2o** [comment]
Hi @Stefanenrichard looks like your logs are a bit messed up

`runbenchmark_20190626T145600.log` : fresh master + docker wrongly enabled. 
`runbenchmark_20190626T151203.log`: fresh master + docker correctly enabled (with still the wrong activation flag in the config though).
`runbenchmark_20190626T152448.log`: same as previous with some old branch.

> Also ensure that you don't have a custom project_repository in that same file, as it's used to pick the default docker image version.

this means, please remove/comment out the `project_repository` in your custom `.config` file otherwise it's likely to try to pull a wrong docker image.
All your logs show `project_repository: https://github.com/openml/automlbenchmark`, this is wrong if you want to use published images, it needs to be: `project_repository: https://github.com/openml/automlbenchmark#stable`, or simply remove it completely from your custom config as this is the default value.

### Docker activation.
Sorry for haven't been clear: when I write `aws.use_docker: true`, I meant it in an hierarchical yaml structure:
```
aws:
   use_docker: true
```
for each config property, please refer to the default `config.yaml`: they're all listed there.

Using correct docker activation + removing `project_repository` in your `config.yaml` this should work (I just double-checked).

**Comment by Stefanenrichard** [comment]
Hi Seb,

Thank you for your explanation. I got AutoSklearn to run from the docker file. Thanks again for all the help!
