### ISSUE TITLE
AutoWEKA probabilities are not sorted correctly

### ISSUE THREAD

**Issue by mfeurer** [openml/automlbenchmark#338]
I was running AutoWEKA with the fix from #333 and found that for some datasets (for example adult and kr-vs-kp) the probabilities are flipped:
```
nowin,won,predictions,truth
0,1,nowin,nowin
0,1,nowin,nowin
0,1,nowin,nowin
0,1,nowin,nowin
0,1,nowin,nowin
0,1,nowin,nowin
0,1,nowin,nowin
0,1,nowin,nowin
0,1,nowin,nowin
0,1,nowin,nowin
0.007,0.993,nowin,nowin
```
which can be seen in the results file where the accuracy is almost one, while the area under curve is almost zero:
```
id,task,framework,constraint,fold,type,result,metric,mode,version,params,app_version,utc,duration,training_duration,predict_duration,models_count,seed,info,acc,auc,logloss
openml.org/t/3,kr-vs-kp,AutoWEKA,3600s8c32G,0,binary,3.91374e-05,auc,singularity,latest,,"dev [NA, NA, NA]",2021-07-05T14:06:47,3415.0,3414.9,,,1483469941,,0.996875,3.91374e-05,33.259
```

**Comment by PGijsbers** [comment]
This seems to be caused by us generating ARFF headers based on the OpenML DataFeatures, which list nominal values in non-deterministic order (that, or the order changed between last Friday and today). Either way we now generate the ARFF files deterministically in alphabetical order (#342) so it should resolve the issue. Please clear your cache for the affected datasets before trying again.
